### ISSUE TITLE
new version has no 0xc0 head

### ISSUE THREAD

**Issue by YToyCoder** [hansSchall/slip-ts#1]
import { encodeSLIP } from "https://deno.land/x/slip_ts@v1.1.2/slip.ts"

const data = Uint8Array.from([1,2,3]);

const encoded: Uint8Array = encodeSLIP(data);
console.log(encoded.toString());

this code output is 1,2,3,192

**Comment by hansSchall** [comment]
By 'new version' you refer to https://jsr.io/@deno-plc/slip, right?

It defenitely implements the packet end (0xc0/192): https://github.com/deno-plc/slip/blob/main/src/slip.core.test.ts

By the way: The new version resides in https://github.com/deno-plc/slip

**Comment by YToyCoder** [comment]
I use "https://deno.land/x/slip_ts@v1.1.2/slip.ts" in deno.
Are we talking about same SLIP? the SLIP I talk about is starting with 0xc0 and end with 0xc0.
This is the test case of this project, it's not starting with 0xc0.
![Snipaste_2024-05-05_16-58-16](https://github.com/hansSchall/slip-ts/assets/59763263/f2f656c3-983e-4004-8ae2-0b0fe541fc68)

**Comment by hansSchall** [comment]
Ok, now I understand.

SLIP usually doesnt use a 0xc0 at the frame start. Some implmentations send a 0xc0 before the first packet in order to terminate everything that was sent before, which can easyly be achieved by sending an empty packet, but this is also the main reason why usually no 0xc0 is sent: It would introduce empty packets between the regular ones. If the application ignores all empty packets this will be fine.

In general an option to add 0xc0 at the frame start sounds usefull to me, so I'll implement it and notify you when it has finished.

**Comment by hansSchall** [comment]
Implemented!

As the repository has moved, updates wont be pushed to deno.land/x, instead you shoud use JSR. Additionally the decoder API has changed (due to some rewriting), but it should be very straitforward to update to @deno-plc/slip

For info on how to use JSR: https://jsr.io/docs/introduction

In a nutshell: `$ deno add @deno-plc/slip` and `import { encodeSLIP } from "@deno-plc/slip"`

or just: `import { encodeSLIP } from "jsr:@deno-plc/slip"`

To use 0xC0 packet starts: `encodeSLIP({terminateStart: true});`
